spring:
  cloud:
    gcp:
      credentials:
        location: classpath:stt.json
  datasource:
    url: jdbc:mysql://localhost:3306/sodam
    username : root
    password : 1102
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG